### ISSUE TITLE
atom-text-editor.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by TixieSalander** [tbremer/px-rem-tooltop-atom#1]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
atom-text-editor.Object.defineProperty.get (/usr/share/atom/resources/app.asar/src/text-editor-element.js:68:18)
change (~/.atom/packages/px-rem-tooltip/lib/pxrem.js:49:18)
<unknown> (~/.atom/packages/px-rem-tooltip/lib/pxrem.js:26:12)
```

**Comment by tbremer** [comment]
Thanks for submitting this, I honestly forgot to check when the version bump occurred.

**Comment by TixieSalander** [comment]
Submitting it was easy, thanks for the quick fix!
