### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lineTextForScreenRow' of undefined

### ISSUE THREAD

**Issue by egonixgit** [tbremer/px-rem-tooltop-atom#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [px-rem-tooltip](https://github.com/tbremer/px-rem-tooltop-atom) package 1.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'lineTextForScreenRow' of undefined

```
At /Users/egon/.atom/packages/px-rem-tooltip/lib/pxrem.js:36

TypeError: Cannot read property 'lineTextForScreenRow' of undefined
    at change (/packages/px-rem-tooltip/lib/pxrem.js:36:22)
    at /packages/px-rem-tooltip/lib/pxrem.js:23:12
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-alignment 0.12.1 
atom-beautify 0.29.17 
atom-live-server 2.1.1 
css-clean 2.19.0 
emmet 2.4.3 
jshint 1.8.6 
language-smarty 1.7.0 
pigments 0.39.0 
platformio-ide-terminal 2.2.3 
px-rem-tooltip 1.3.0 
rest-client 1.3.1 
turbo-javascript 1.4.0 
```

**Comment by tbremer** [comment]
Thanks for filing a bug, can you help me with context of how the error occurred?

Was it a new file, existing file, empty lines? Anything?

Thanks!

**Comment by egonixgit** [comment]
Sry No,

Error just popedup during Atom startup. And since I’was on a deadline I just went on working. :(

**Comment by tbremer** [comment]
No worries. I'll leave the issue open so I can keep it in mind, but I can't replicate it.

If you see it again can you try to document what is going on?

Like, if files were open or something?

Thanks!
